services:
  - type: web
    name: whatsapp-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python whatsapp_bot.py
    envVars:
      - key: NUMVERIFY_API_KEY
        value: f4ddf206a158a144437617bdf02320b0

